"""
Video Editing Plugin
==================
Auto-generated by AMARTIE Research Crew.
Recommended tool: FFmpeg
URL: https://ffmpeg.org
Platforms: macos, linux, windows
"""

import json
import os
import subprocess
import platform

PLUGIN_NAME = "Video Editing"
PLUGIN_VERSION = "0.1.0"
PLUGIN_DESCRIPTION = "Video production and editing"
STUDIO_TYPE = "video_edit"

# Tool configuration
TOOL_NAME = "FFmpeg"
TOOL_URL = "https://ffmpeg.org"
TOOL_API = "CLI + libraries"
PLATFORMS = ['macos', 'linux', 'windows']

# OS-specific setup
OS_SETUP = {
    "macos": {
        "install": "brew install --cask ffmpeg",
        "check": "which ffmpeg",
        "notes": "Install via Homebrew"
    },
    "linux": {
        "install": "sudo apt install ffmpeg || sudo snap install ffmpeg",
        "check": "which ffmpeg",
        "notes": "Install via apt or snap"
    },
    "windows": {
        "install": "choco install ffmpeg || winget install ffmpeg",
        "check": "where ffmpeg",
        "notes": "Install via Chocolatey or winget"
    }
}


def render(config=None):
    return {
        "name": PLUGIN_NAME,
        "version": PLUGIN_VERSION,
        "type": STUDIO_TYPE,
        "html": get_studio_html(),
        "scripts": get_studio_scripts(),
        "config": config or {}
    }


def handle(action, data):
    if action == "install":
        return install_tool()
    elif action == "check":
        return check_tool()
    elif action == "run":
        return run_tool(data)
    return {"error": "unknown action"}


def get_current_os():
    """Detect the current operating system."""
    system = platform.system().lower()
    if system == "darwin":
        return "macos"
    return system


def install_tool():
    """Install the recommended tool for the current OS."""
    os_name = get_current_os()
    if os_name not in OS_SETUP:
        return {"error": f"Unsupported OS: {os_name}"}
    
    setup = OS_SETUP[os_name]
    try:
        result = subprocess.run(
            setup["install"],
            shell=True,
            capture_output=True,
            text=True,
            timeout=60
        )
        return {
            "status": "install attempted",
            "os": os_name,
            "output": result.stdout,
            "errors": result.stderr
        }
    except Exception as e:
        return {"error": str(e)}


def check_tool():
    """Check if the tool is installed."""
    os_name = get_current_os()
    if os_name not in OS_SETUP:
        return {"error": f"Unsupported OS: {os_name}"}
    
    setup = OS_SETUP[os_name]
    try:
        result = subprocess.run(
            setup["check"],
            shell=True,
            capture_output=True,
            text=True,
            timeout=10
        )
        found = result.returncode == 0
        return {
            "installed": found,
            "os": os_name,
            "path": result.stdout.strip() if found else None,
            "install_command": setup["install"],
            "notes": setup["notes"]
        }
    except Exception as e:
        return {"error": str(e)}


def run_tool(data):
    """Run the tool with parameters."""
    action_type = data.get("action", "open")
    
    if action_type == "open":
        os_name = get_current_os()
        if os_name == "macos":
            cmd = f"open -a 'FFmpeg'"
        elif os_name == "linux":
            cmd = f"ffmpeg &"
        elif os_name == "windows":
            cmd = f"start ffmpeg"
        else:
            return {"error": f"Unsupported OS: {os_name}"}
        
        try:
            subprocess.Popen(cmd, shell=True)
            return {"status": "launched", "command": cmd}
        except Exception as e:
            return {"error": str(e)}
    
    return {"error": f"Unknown action: {action_type}"}  # Fixed placeholder


def get_studio_html():
    return """
<div class="studio-generic">
  <h2>Video Editing</h2>
  <p class="muted">Video production and editing</p>
  <div class="tool-info">
    <div class="tool-name">Recommended: <a href="https://ffmpeg.org" target="_blank">FFmpeg</a></div>
    <div class="tool-api">API: CLI + libraries</div>
    <div class="tool-platforms">Platforms: macos, linux, windows</div>
  </div>
  <div class="row"><label>How to use</label>
    <textarea id="studio-prompt" rows="4" placeholder="Describe what you want to create..."></textarea>
  </div>
  <button onclick="studioCheck()">Check Installation</button>
  <button onclick="studioInstall()">Install Tool</button>
  <button onclick="studioRun()">Run Tool</button>
  <div id="studio-status"></div>
</div>
"""


def get_studio_scripts():
    return """
async function studioCheck() {
  const res = await cockpit.pluginAction('video_edit-studio', 'check', {});
  document.getElementById('studio-status').textContent = 
    res.installed ? 'Installed: ' + res.path : 'Not installed. ' + res.notes + ' Run: ' + res.install_command;
}
async function studioInstall() {
  const res = await cockpit.pluginAction('video_edit-studio', 'install', {});
  document.getElementById('studio-status').textContent = res.status || res.error;
}
async function studioRun() {
  const res = await cockpit.pluginAction('video_edit-studio', 'run', {action: 'open'});
  document.getElementById('studio-status').textContent = res.status || res.error;
}
"""
